### ISSUE TITLE
The number of Average Interest Rate isn't match

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#109]
There is a page that the Average Interest Rate is incorrect.

For example, the Average Interest Rate of 0xFcA9b9b3fdC7C809FcF9f6620Bb39D19abC8BA8f is `0.22757155663023132%`.

Main page:
![image](https://user-images.githubusercontent.com/1970283/80325582-b73a7e00-8870-11ea-9e93-1de206a19962.png)

Property page:
![image](https://user-images.githubusercontent.com/1970283/80325591-c1f51300-8870-11ea-8732-d9e483308b91.png)

---

## The source of `0.22757155663023132%`

1. Query the Metrics addresses from the Property address:

```gql
{
  property_authentication(where: {property: {_eq: "0xFcA9b9b3fdC7C809FcF9f6620Bb39D19abC8BA8f"}}) {
    metrics
  }
}
```

The response:
```json
{
  "data": {
    "property_authentication": [
      {
        "metrics": "0x1dc0DAd66474f5D551170910db47e4AB5801Fcf2"
      }
    ]
  }
}
```

2. Query the sum of Staking Rewards and Locked Up amount from the Metrics addresses:

```gql
{
  reward_calculation_result_aggregate(where: {block_number: {_gt: 9600000}, metrics: {_in: ["0x1dc0DAd66474f5D551170910db47e4AB5801Fcf2"]}}) {
    aggregate {
      sum {
        staking_reward
        lockup
      }
    }
  }
}
```

The response:

```json
{
  "data": {
    "reward_calculation_result_aggregate": {
      "aggregate": {
        "sum": {
          "staking_reward": 113785778315115660,
          "lockup": 50000000000000000000
        }
      }
    }
  }
}
```

3. Calculate the rate:

```
113785778315115660 / 50000000000000000000 * 100 = 0.22757155663023132
```
https://www.wolframalpha.com/input/?i=113785778315115660%2F50000000000000000000*100+

**Comment by k3nt0w** [comment]
@aggre 
Thank you for your writing detail about this issue:pray: I' going to resolve this problem from now.
