### ISSUE TITLE
DEV Treasury Landing Page

### ISSUE THREAD

**Issue by defi-er** [dev-protocol/stakes.social#1110]
Create a landing page that shows what tokens the DEV treasury holds

**Comment by defi-er** [comment]
@hhatto can you build the backend functionality to show which projects have paid the OSS Treasury fees?

cc: @aggre

**Comment by hhatto** [comment]
@defi-er 
By combining the existing functions, it is possible to get the DEV Treasry value for each property with only a few changes.

The red boxes below show the values(this change on my local environement):
<img width="1427" alt="treasury-dev-per-property" src="https://user-images.githubusercontent.com/150309/111954165-06456d80-8b2b-11eb-9f61-42cc911239b1.png">

can also get the total value, though it may be a bit slower.

**Comment by hhatto** [comment]
this feature has been released.
