### ISSUE TITLE
Visiting https://stakes.social/incubator returns "An unexpected error has occurred."

### ISSUE THREAD

**Issue by gem1no** [dev-protocol/stakes.social#1146]
Windows 10
- [x] Brave
- [x] Chrome
- [x] Microsoft Edge (lol)
![Capture](https://user-images.githubusercontent.com/64822997/112255431-8c030f00-8c38-11eb-9127-1567f19c0390.PNG)

**Comment by kazu80** [comment]
Thank you for reporting! We fixed now
