### ISSUE TITLE
Allow users to create usernames for themselves (Block Profanity)

### ISSUE THREAD

**Issue by defi-er** [dev-protocol/stakes.social#1152]
Allow all users to add a name for themselves. Use Google Profanity words to prevent users from adding profanity to their name. [Google Profanity Words-Github](https://github.com/RobertJGabriel/Google-profanity-words)

**Comment by hhatto** [comment]
[implementation notes]
use npm package https://www.npmjs.com/package/google-profanity-words.
The words defined are the same.
