### ISSUE TITLE
Add an option for stake badge to show the project staking amount

### ISSUE THREAD

**Issue by talentlessguy** [dev-protocol/stakes.social#1181]
For example:

```
https://badge.devprotocol.xyz/<address>/descriptive?totalStaking=true
```

will show the total staking amount

**Comment by hhatto** [comment]
Thanks for feedback.

It already shows the total staking amount, is it a different number than this?
If it is 0, it will be displayed as `-`.

for example:
<img width="131" alt="dev-badge" src="https://user-images.githubusercontent.com/150309/114324489-3ea5fd80-9b65-11eb-9e7c-619bc636a47d.png">

for example with zero DEV:
<img width="104" alt="dev-badge-zero" src="https://user-images.githubusercontent.com/150309/114324527-83319900-9b65-11eb-8955-be1a5c8948a2.png">

**Comment by talentlessguy** [comment]
@hhatto oops sorry, closing the issue then
