### ISSUE TITLE
A Tutorial Guide for Crypt Beginners

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1367]
If a beginner is using Ethereum for the first time, they are often confused about what to do when they visit Stakes.social.

I think we need a tutorial guide for beginners so that they can use Stakes.social with ease. That page will work for "read this first."

What kind of content do we need for that page? I think it would be very helpful if interactions such as wallet connection could actually be manipulated. What kind of interactions do we need for that page?

**Comment by kazu80** [comment]
I think the idea to solve this is to change the content posted on the TOP page of Stakes.social.
First of all, I would like to submit the design of the TOP page that I think
