### ISSUE TITLE
"execution reverted: insuffiecient tokens" when setting a custom withdraw amount

### ISSUE THREAD

**Issue by talentlessguy** [dev-protocol/stakes.social#1385]
when I try to withdraw a custom value of DEV I see this:

![image](https://user-images.githubusercontent.com/35937217/121714199-47279f80-cae6-11eb-8635-6bbabbeba056.png)

**Comment by hhatto** [comment]
@talentlessguy 

Thanks for reporting.
Resolved by PR #1384 .

**Comment by iamxyzone** [comment]
Noonce

**Comment by hhatto** [comment]
resolved
