### ISSUE TITLE
Error: Returned error: Your app has exceeded its compute units per second capacity.

### ISSUE THREAD

**Issue by talentlessguy** [dev-protocol/stakes.social#1538]
Whenever I sign in to stakes.social I get this error on login

![image](https://user-images.githubusercontent.com/35937217/128628872-c9c05f10-a226-47ff-afb9-f90e5f045d76.png)

Dapp continues to function but this is not cool for UI/UX anyway

**Comment by hhatto** [comment]
related issue: #1438 #1553
