### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/stakes.social#1551]
The broken link was reported by a community member

![image](https://user-images.githubusercontent.com/73097560/128961570-ffa0e4ae-b3ad-48ee-8cc5-8ffe31d11392.png)

**Comment by kazu80** [comment]
I can't find link 'https://docs.devprotocol.xyz/protocol/tokenomics'
I will link to 'https://docs.devprotocol.xyz/introduction/'

**Comment by vinzvinci** [comment]
The topic is here: https://docs.devprotocol.xyz/introduction/devtoken/

**Comment by kazu80** [comment]
Thanks. Ill do
