### ISSUE TITLE
returned error

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/stakes.social#1553]
This shows when I open the page: http://stakes.social/

![image](https://user-images.githubusercontent.com/73097560/128966287-f2da8f95-7398-4ab3-8963-b865218607b7.png)

**Comment by kazu80** [comment]
This error depend on alchemyapi.
We need refactor code for decreases call api.
or That error display move to console.log

**Comment by vinzvinci** [comment]
I see. This should be fix

**Comment by hhatto** [comment]
related issue #1438

**Comment by vinzvinci** [comment]
Thanks, I will close this issue.
