### ISSUE TITLE
Supports sTokens

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1603]
Staking and withdrawal UIs have to supports sTokens.

## For staking UI

Requirements:
- Select "Create a new staking position" and "Update an existing staking position."
- If a user chooses "Create a new staking position," the user sends an `approve` transaction first, then staking.
- If a user chooses "Update an existing staking position," the user enters owned staking position's token ID, sends an `approve` transaction, and then staking.

### UI
<img width="255" alt="Stake" src="https://user-images.githubusercontent.com/1970283/132007536-16b0e35f-6a0b-4781-bd95-c3400b0932bf.png">

## For withdrawal UI

Requirements:
- A user enters owned staking position's token ID, enters the withdrawal amount, and then withdraws.

### UI
<img width="255" alt="Withdraw" src="https://user-images.githubusercontent.com/1970283/132007578-7129b8b3-a701-4d7c-8340-53324c213e74.png">

## For convert to sTokens UI
<img width="324" alt="Convert" src="https://user-images.githubusercontent.com/1970283/132007652-c923b5b1-a513-4f68-a915-c308433f56bb.png">

---

**Comment by aggre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sTokens](https://trello.com/c/H6bNUScR/1-stokens)

**Comment by aggre** [comment]
The latest Dev Kit JS uses Ethers.js, for the time being, it would be nice to Stakes.social uses Web3.js and bridging to Ethers.js.

Below the just my idea:
- All code that calling Ethereum network, continue using Web3. E.g., `const {web3} = useProvider()`
- Which using Dev Kit JS, the Web3 instance wraps with Ethers. E.g.,
```ts
const {web3} = useProvider()
const prov = new providers.Web3Provider(web3.currentProvider)
return contractFactory(prov)
```
https://github.com/dev-protocol/stakes.social/blob/a7ed3c5c7e4e71ba85788e0b10ef04d61ad321b7/packages/web/src/fixtures/dev-kit/client.ts#L21

But I don't know the code is workes fine 🙃

**Comment by aggre** [comment]
To minimize changes to Stakes.social, we've decided to maintain the Web3 version of Dev Kit JS for the foreseeable future. And this is a Japanese document that summarizes the changes.

https://paper.dropbox.com/doc/Stakes.social-updates-for-sTokens--BR0lpJ5yFHxONVb19VjCI1L1AQ-cpkLZ6oWEIteSSbF2RYTx

**Comment by k3nt0w** [comment]
@aggre 

I don't think it's a good UI for users to have text ( `Add the existing positions` ) between radio buttons. It also makes the implementation more complicated, so I'd like to avoid it if I can. Should I follow this wire UI? Or is there a possibility to improve the UI further?

![](https://user-images.githubusercontent.com/1970283/132007536-16b0e35f-6a0b-4781-bd95-c3400b0932bf.png)

**Comment by aggre** [comment]
@k3nt0w Super cool!! LGTM ;)

**Comment by k3nt0w** [comment]
@aggre 
OK, Thanks. For now, I'll submit a Pull Request with the text removed.

**Comment by hhatto** [comment]
this feature has been released 👍
