### ISSUE TITLE
Remove onboarding-sponsor banner

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/stakes.social#1620]
Remove 

![image](https://user-images.githubusercontent.com/73097560/131605448-be5da1d9-cfe7-4876-a718-4f8acc398724.png)

**Comment by vinzvinci** [comment]
We are using SVG on this: https://github.com/dev-protocol/onboarding-sponsor/blob/main/static/images/sponsors/sponsors.svg

Does anyone have copy of a software where to edit SVG?

**Comment by Ryjin210** [comment]
> We are using SVG on this: https://github.com/dev-protocol/onboarding-sponsor/blob/main/static/images/sponsors/sponsors.svg and SIOS is already here.
> 
> Does anyone have copy of a software where to edit SVG? or other SVG we can change to this?
> I like to remove Onboarding Sponsors

I think I can help you with that. I'll try to give it a go

**Comment by vinzvinci** [comment]
Nice! @Ryjin210 :) that will be a big help!

**Comment by vinzvinci** [comment]
Done: https://onboarding-sponsors.devprotocol.xyz/images/sponsors/sponsors.svg
