### ISSUE TITLE
[BUG] Stakes Social

### ISSUE THREAD

**Issue by pdotall** [dev-protocol/stakes.social#1811]
### Description

This is the best place to report bugs/problems that stakers find on stakes.social.

Few Comments I made 2 days ago:

>  there is a typo at the bottom of the page saying 'But DEV on...' instead of ' Buy DEV on...' 
FIXED

> I managed to move the funds to L2 but... when I staked, there is no confirmation about my position, the stoken position doesn't show and I can interact with the pool and withdraw my rewards.  My position doesn't show on the UI and neither does the rewards
FIXED

> the APY went from 1700% to 5% when I staked
100000 DEV were sent to L2 and the APY went to 55%

* If the wallet isn't connected you can't see the APY% on the website, it's just blank

* APY on L1 is getting way too attractive for anyone to move to L2 

Last 2 points are still standing.

![image](https://user-images.githubusercontent.com/84878611/140611144-26563813-2a4a-4b9e-925d-02da4bf09eaf.png)

and 

APY on Ethereum Mainnet > APY on Arbitrum

![image](https://user-images.githubusercontent.com/84878611/140611196-2d29939c-5eda-4481-b6b6-d80e53ea4190.png)
(ARBITRUM ONE)

![image](https://user-images.githubusercontent.com/84878611/140611215-313fa164-a3e1-4b99-8d32-041e759aadf3.png)
(ETHEREUM MAINNET)

### Expected behavior/contents

It is interesting to show the APY% even without connecting a wallet.

IF we want to create an incentive so that people move from L1 to L2, APY on L1 should be significantly lower and/or APY on L2 higher.

On the community forum and discord I have predicted this would happen and the proposed solution is there.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pdotall** [comment]
Current difference between L1 and L2 getting bigger, when it should be the opposite, L2>L1.

**Comment by samuil4** [comment]
Hi, when will the APY on L2 be fixed. Currently it is very low!

**Comment by aggre** [comment]
Stakes.social's inability to show content when a wallet is not connected is a bug that should be fixed.

I think the discussion about APY should be separated from Stakes.social, and the discussion should be moved to the forum. (I'll open a topic later)

**Comment by aggre** [comment]
I've posted: https://community.devprotocol.xyz/t/different-inflations-on-different-networks/395
