### ISSUE TITLE
[FEATURE] Remove gas fee estimation feature

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1878]
### Detailed description

I may receive an error message similar to the following:
```
cannot estimate gas; transaction may fail or may require manual gas limit (error={"message":"execution reverted","code":-32000}, method="call", transaction={"to":"0x1A2B49e10013C40AAC9b6f9e785837bfd329e5e0","data":"0x56891412","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)
```

I suggest removing the gas fee estimation feature itself.

### Context

Due to multi-network support, the gas fee estimation feature often fails. This is often the case with many early-stage L2s such as Arbitrum.

Is it correct to display "Estimation failed" on the UI when the gas fee estimation fails? I think it only makes users uneasy.

Therefore, I think it is better to remove the gas fee estimation feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phryneas** [comment]
Assuming that this is actually connected, after that error message was shown the whole page stops working - and for me personally that error message is shown on every navigation while being logged in, multiple times after each other.

[screenshot of the pool overview](https://i.imgur.com/ze2YqcP.png)

As I have not found out how to look at the L2 pools without being logged in yet, I cannot use any L2-related features on the page at all - it only works while I'm logged out.
