### ISSUE TITLE
[OTHER] Renew hero component

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1900]
### What would you like to share?

Replace the first view of the Property page with the following new hero component.

![Web capture_3-12-2021_15292_aggregqor4 proto io](https://user-images.githubusercontent.com/1970283/144556053-a0ed960d-2283-465a-a040-50b4a59b8899.jpeg)
https://pr.to/4K1MQA/

The new hero component replaces this view:
![image](https://user-images.githubusercontent.com/1970283/144555665-ed2a381a-3c70-4518-8a8c-2565103d2874.png)

### Additional information

The following child components can be implemented by other issues:
- Favorite button
- Share button
- Stake button
- Claim button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
[dev-for-apps](https://github.com/dev-protocol/dev-for-apps/) needs to support Property Tokens avatar images.

**Comment by aggre** [comment]
I expect this feature to be merged into `preview` branch and published as preview.stakes.social.

**Comment by hhatto** [comment]
related issue: https://github.com/dev-protocol/stakes.social/pull/1504

feature of property tags

**Comment by hhatto** [comment]
@aggre 

I have one question.

I think the image on the top left is the Property Tokens avatar images, are these different from the previous cover images? Will I no longer use the cover image?
