### ISSUE TITLE
[BUG] Already stacked large amount of DEV

### ISSUE THREAD

**Issue by arab-nerd** [dev-protocol/stakes.social#1909]
### Problem subject

0x1a2b49e10013c40aac9b6f9e785837bfd329e5e0

### Description

To avoid arbitrum gas fees I approved access to large amount of DEV But staking form still ask for approval (every access approval cost 7$)

### Expected behavior/contents

Staking form should checks if required amount already approved don't ask for access approval again

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
This problem has already been recognized and I too hope that it will be resolved.

**Comment by aggre** [comment]
Maybe just check the user's allowance at the next state change:
https://github.com/dev-protocol/stakes.social/blob/b809afd49d5fb10eeb75d0e90acb61a2ce774d2a/packages/web/src/components/organisms/Stake/index.tsx#L187
