### ISSUE TITLE
[BUG] `cannot estimate gas; transaction may fail or may require manual gas limit (error={"message":"execution reverted","code":-32000}, method="call", transaction=<THE_TX>, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)` error occurs when trying to connect to Arbitrum with MetaMask for Android via WalletConnect

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1928]
### Problem subject

- [x] Web app

### Description

The following error was reported [on Discord](https://discord.com/channels/547215761341546497/701644482126544926/917491475045056512):
![](https://i.imgur.com/ze2YqcP.png)

This error occurs when trying to connect to Arbitrum with MetaMask for Android via WalletConnect.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phryneas** [comment]
Since the problem is occuring for me, if you need me to test a fix or something, contact me.
