### ISSUE TITLE
[FEATURE] Check allowance

### ISSUE THREAD

**Issue by hhatto** [dev-protocol/stakes.social#1942]
@aggre edited this issue to give a more detailed explanation of what this issue should solve.

The title of this issue says "for withdraw", but it's actually intended to fix a bug for staking.

## Actual behavior
In order to execute "Stake", the user must call `approve` for the Lockup contract, every time.

## Expected behavior
A user who has given a sufficient allowance of DEV to the Lockup contract should not need additional action for staking.

## Reference information
In the source code, the Stake component seems to be trying to fetch the allowance to achieve the expected behavior:
https://github.com/dev-protocol/stakes.social/blob/c7c3cee4796b1c77d2d917fd2198d628a4b6ed66/packages/web/src/components/organisms/Stake/index.tsx#L148-L157

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
We have started a bounty for this issue!

https://app.chainwhiz.app/bounty/61f8897ee60b5800180d9411
