### ISSUE TITLE
Image replacing feature for sTokens

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1953]
## Routing
If I design it, I would route it like this:
```
/positions/[token_id]/
```

In the future, the page will have more features, and I think it will change as follows:
```
/positions/[token_id]/edit
```

Of course, it is completely under the control of a developer.

## Main UI parts
- Table for the staking position
- Image accessor: Only used to access an image file, **not uploads**
- Attach and Attach with IPFS: When clicking the "Attach" button, base64-encodes the image and calls `STokens.setTokenURIImage`. When clicking the "Attach with IPFS" button, pushes the image to IPFS and calls STokens.setTokenURIImage with its hash value.

## Mock up
![image](https://user-images.githubusercontent.com/1970283/146307142-ff6ea021-55c8-43fe-9033-7150dcad2e38.png)
https://pr.to/4K1MQA/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hhatto** [comment]
done
