### ISSUE TITLE
React Hook for uploading image to IPFS via nft.storage

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1954]
### What would you like to share?

[The UI](https://github.com/dev-protocol/stakes.social/issues/1953), when "Attach with IPFS" is clicked, needs a React Hooks function that pushes the image to IPFS and returns its hash value.

IPFS can't persist a file without pinning it, so use nft.storage to delegate file persistence to the service.

Doc at nft.storage: https://nftstorage.github.io/nft.storage/client/

## Expected interface
This Hooks function returns a function that calls `useCallback`.
Similar existing Hook, useStake: https://github.com/dev-protocol/stakes.social/blob/1979957709ad7cdf8b16df9326ebdc17142480c1/packages/web/src/fixtures/dev-kit/hooks.ts#L332-L359

- The input value of the returned function: File blob
- The return value of the returned function: IPFS address (like: `ipfs://eyxcd...`)

**_Of course, it is completely under the control of a developer._**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hhatto** [comment]
done
