### ISSUE TITLE
React Hook for obtain an image path

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#1955]
### What would you like to share?

One of the sTokens metadata properties, "image", has roughly two formats:
- Base64: Like `data:image/png;base64,<DATA>`, `data:image/jpeg;base64,<DATA>`, and other image types
- IPFS: `ipfs://<CID>`

Base64 can be used for `src` attribute of `img` element, but IPFS cannot. So for IPFS we need a React Hooks function that rewrites the image path as base64.

## Expected interface
This Hooks function returns base64 encoded string using SWR caching.
Similar existing Hook, useGetStokenSymbol: https://github.com/dev-protocol/stakes.social/blob/1979957709ad7cdf8b16df9326ebdc17142480c1/packages/web/src/fixtures/dev-kit/hooks.ts#L1097-L1106

- The input value of the returned function: Base64 or IPFS URL
- The return value of the returned function: Base64

**_Of course, it is completely under the control of a developer._**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hhatto** [comment]
done
