### ISSUE TITLE
[FEATURE] Rename name to username

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/stakes.social#2031]
### What would you like to share?

Change this to Discord username: 

![image](https://user-images.githubusercontent.com/73097560/148775198-a4bb5133-182a-48f1-8d89-318d7c58eff2.png)

Link: https://discord.com/channels/547215761341546497/917968007198830653/930079049513066506

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acjr1910** [comment]
Hi! Can I work on this feat?

<img width="530" alt="username" src="https://user-images.githubusercontent.com/28766927/148781570-13186102-9027-4f66-b9fc-389b0f6c6518.png">

Is this fine?

**Comment by vinzvinci** [comment]
> Hi! Can I work on this feat?
> 
> <img alt="username" width="530" src="https://user-images.githubusercontent.com/28766927/148781570-13186102-9027-4f66-b9fc-389b0f6c6518.png">
> 
> Is this fine?

Yeah cool for me. 

P.s
I mistakenly edit your comment lol

**Comment by acjr1910** [comment]
Cool!
I have raised the PR for this: #2032
