### ISSUE TITLE
[FEATURE] Buy DEV button uses a modal

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#2045]
### Detailed description

After clicking the Buy DEV button, use a [modal dialog](https://ant.design/components/modal/) to guide the user to the appropriate DEXs for multiple networks.

![image](https://user-images.githubusercontent.com/1970283/149048206-7f82fcdb-8ddd-454f-88f2-a08bedb22f49.png)

### DEXs:
| Network | Link |
|---|---|
| Polygon | https://quickswap.exchange/#/swap?outputCurrency=0xA5577D1cec2583058A6Bd6d5DEAC44797c205701 |
| Arbitrum | 1. Access https://app.uniswap.org/#/swap<br/>2. Select Arbitrum with the network selector<br/>3. Click Select a token and input `0x91F5dC90979b058eBA3be6B7B7e523df7e84e137` | 
| Ethereum | https://app.uniswap.org/#/swap?outputCurrency=0x5caf454ba92e6f2c929df14667ee360ed9fd5b26&use=V2 |

### Context

The Buy DEV button always opens Uniswap on the mainnet no matter which network the user is connected to.

In fact, Dev Protocol supports Ethereum, Arbitrum, and Polygon, so it's better to guide the user to the appropriate DEXs for multiple networks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krshdev** [comment]
I'd love to work on this.

**Comment by aggre** [comment]
We have started a bounty for this issue!

https://app.chainwhiz.app/bounty/61f88b54e60b5800180d9412
