### ISSUE TITLE
[OTHER] Network selector on the frontpage

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#2048]
### What would you like to share?

The fact that Dev Protocol is already multi-chain capable is not apparent from the first view.

Putting a component similar to the network selector in the navigation on the front page will make it easier for users to know the multi-chain.

This is a simple mockup created in the browser inspector:
![image](https://user-images.githubusercontent.com/1970283/149060458-5a0db4ba-4358-45ae-90a9-7944e2af3ca0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
We have started a bounty for this issue!

https://app.chainwhiz.app/bounty/61f8945de60b5800180d941a

**Comment by rajashree23** [comment]
I have a few doubts, can someone clarify them?

1. To my knowledge, the component should only have the network name displayed. 
2. There shoudln't be any **connect** button functionality,unlike navbar, right?

**Comment by aggre** [comment]
> There shouldn't be any **connect** button functionality, unlike navbar, right?

@rajashree23 Yes, in my opinion, there is no connect button there.
