### ISSUE TITLE
Want to show authentication results

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#206]
Dev Kit returns a new Metrics address when Promise in "Market. Authenticate" resolves.

To better UX, replace the AuthForm by the [Result](https://ant.design/components/result/
) component, once Promise is resolved.

For example:
```tsx
  <Result
    status="success"
    title="Successfully Authenticated Your Asset!"
    subTitle="Viewing a new asset will take dozens of minutes, but you can also check it out right away on Etherscan."
    extra={[
      <Button href={`https://etherscan.io/address/${THE_NEW_METRICS_ADDRESS}`}>
        Etherscan
      </Button>,
      <Button href={`/${THE_PROPERTY_ADDRESS}`} type="primary">
        Go the Property
      </Button>
    ]}
  />
```

**Comment by k3nt0w** [comment]
@aggre 
Sorry, I didn’t watch this issue. Thank you for your commit🙇‍♂️

Can we close this issue??

**Comment by aggre** [comment]
@k3nt0w Not a problem thanks for your basic code! I close this.
