### ISSUE TITLE
[FEATURE] App Header Cleanup

### ISSUE THREAD

**Issue by stuartwk** [dev-protocol/stakes.social#2338]
### Detailed description

New design mocks to simplify header
![header-mock](https://user-images.githubusercontent.com/11183054/162662005-951e6d46-1c01-4583-8e7f-2d28e85913ee.png)

### Context

Simplifies navigation and strip outs some of the antd in favor of Tailwind

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Closing this issue now. Thanks for your contributions 🎉
