### ISSUE TITLE
[BUG] Error when trying to select a polygon network

### ISSUE THREAD

**Issue by osaguild** [dev-protocol/stakes.social#2429]
### Problem subject

- when I select a polygon network on the "stakes.social" an error has occurred
- I want to stake using the polygon network but it does not work

### Operation
- access `https://stakes.social/`
- select "polygon" network
- connect the wallet using connect button on the navigation bar
- error occurred

### Error message
- `call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="symbol()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.0)`

### Capture
![Screen Shot 2022-05-09 at 14 13 41](https://user-images.githubusercontent.com/33506754/167344843-657d9f9e-09bd-4442-a54b-24b80e33e771.png)

### Expected behavior/contents

- can connect to the  polygon network without error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Hi @osaguild, do u want to work with this?

**Comment by osaguild** [comment]
Hi @vinzvinci, I will try it. Maybe my metamask setting is the cause.
