### ISSUE TITLE
IDEA: Stakers Dashboard

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#369]
I am thinking of needing a feature like a "Stakers Dashboard" to more useful staking.

It features the following UI. (I think that design will use [this component](https://ant.design/components/table/#components-table-demo-multiple-sorter))

---

### My Staking Properties

Property | Staking amount | Staked day | Elapsed days | Withdrawable rewards | Total earned | Cancel
-- | -- | -- | -- | -- | -- | --
@devprtcl/dev-kit-js | 4000DEV | 6/20/2020 | 48 days 12h 42 min xx | 25 DEV [withdraw] | 124.48 DEV | [Cancel] [withdraw]
vue-i18n | 2100DEV | 7/4/2020 | 28 days 3h 19 min xx | 11 DEV [withdraw] | 52.1 DEV | [Cancel] [withdraw]
  |   |   |   |   |   |  

### Summary 

`My Staking Properties: 5` | `Total Staking Amount: 203K DEV` |  `Total Earned: 483 DEV`

---

I want to discuss it together here.

Are there unnecessary or more needed pieces of information?

**Comment by calaber24p** [comment]
I like this idea a lot and would be happy to see it implemented
