### ISSUE TITLE
New header design

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#513]
Implement the new header design.

![image](https://user-images.githubusercontent.com/1970283/93409109-186ef680-f8d1-11ea-928f-0788b0b5784f.png)

**Comment by hhatto** [comment]
Also, need to show `Login` if the user is not logged in at the `Account` part, and show `Account` if the user is already logged in.
also need to add a login process (showing the dialog for the wallet to connect to).

**Comment by aggre** [comment]
Wallet connection dialog should be a separate issue. So I close this issue.
