### ISSUE TITLE
Dev Protocol Stats

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#528]
Implement the Dev Protocol Stats page.

![image](https://user-images.githubusercontent.com/1970283/93420388-c1295000-f8e9-11ea-9553-37d42e4ac030.png)

**Comment by aggre** [comment]
The data source for this page was intended to be https://thegraph.com.

But I'm not yet familiar with The Graph's API.

I'm going to do some research now, so until then, you might as well proceed with building the UI with mocked data.

**Comment by aggre** [comment]
@Akira-Taniguchi Can you review The Graph's API? I'd be happy to find out if we can use it, and if so, what queries we can use to achieve this dashboard.

**Comment by Akira-Taniguchi** [comment]
It looks like we'll be getting DEV data mainly from uniswap.
We'll investigate.

**Comment by Akira-Taniguchi** [comment]
*一旦日本語で。あとで訳す


参考ページ
https://uniswap.org/docs/v2/API/overview/
https://uniswap.org/docs/v2/API/entities/
https://uniswap.org/docs/v2/API/queries/

[はじめに]
毎回Uniswapにクエリ投げる仕様は、Uniswap側に付加対策とかされると詰むので、
こちらで定期的(1分ごとぐらい?)にクエリ投げて、必要な計算して、内部DB(postgresとか)に保存して、
stake socialからは独自のAPIを実行し、内部DBに保温した値を返す、みたいな仕様にした方がいい気がする

[DEV MARKET CAP]
1.DEVコントラクト のtotal_supplyを取得
2.Uniswapに下記クエリを投げて、1DEVトークンのUSDでの値段を日毎で取得
　(limitの掛け方がまだわからない。。。)
{
  tokenDayDatas(orderBy: date, orderDirection: desc,
    where: {
     token: "0x5caf454ba92e6f2c929df14667ee360ed9fd5b26"
    }
  ) {
   id
   date
   priceUSD
  }
}
3.1と2をかける

[DEV PRICE]
1.Uniswapに下記クエリを投げて、1DEVトークンのUSDでの値段を日毎で取得
　(limitの掛け方がまだわからない。。。)
{
  tokenDayDatas(orderBy: date, orderDirection: desc,
    where: {
     token: "0x5caf454ba92e6f2c929df14667ee360ed9fd5b26"
    }
  ) {
   id
   date
   priceUSD
  }
}
2.前日比を出したければ、その都度計算

[DEV StAKED RATIO]
1.DEVコントラクト のtotal_supplyを取得
2.Lockupコントラクト のgetAllValueを取得
3.2わる1✖︎100で算出

[STAKED DEV VALUE]
1.Lockupコントラクト のgetAllValueを取得
2.Uniswapに下記クエリを投げて、1DEVトークンのUSDでの値段を取得
　(limitの掛け方がまだわからない。。。)
{
  tokenDayDatas(orderBy: date, orderDirection: desc,
    where: {
     token: "0x5caf454ba92e6f2c929df14667ee360ed9fd5b26"
    }
  ) {
   id
   date
   priceUSD
  }
}
3.1と2をかける

[CREATOR APY]
今のstakes.socialsのやり方をそのまま利用する

[STAKER APY]
今のstakes.socialsのやり方をそのまま利用する

[ASSETS ONBOARDED]
1.弊社GraphQLエンジンに下記クエリを投げて取得する
{
  "data": {
    "property_authentication_aggregate": {
      "aggregate": {
        "count": 1585
      }
    }
  }
}

**Comment by hhatto** [comment]
@aggre @Akira-Taniguchi 
Thank you for your help.
I just have one more question.

Is it possible to get the `CREATOR'S REWARDS DEV` from dev-kit or graphql?
Is this the value you need to implement a custom resolver?

**Comment by aggre** [comment]
@hhatto "CREATOR'S REWARDS DEV" is calculated by the `Total amount of staking * Creator's APY`.

"Total amount of staking" is can be fetched by "Lockup.getAllValue" of Dev Kit JS: https://github.com/dev-protocol/dev-kit-js/blob/main/lib/lockup/getAllValue.ts

**Comment by hhatto** [comment]
@aggre 
I see. Thanks!! 👍
