### ISSUE TITLE
Wallet Connection Dialog

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#575]
Implementation of the wallet connection dialog.

![image](https://user-images.githubusercontent.com/1970283/95005226-78cf9900-0630-11eb-81a2-8c8e78d2b73a.png)

**Comment by aggre** [comment]
- Browser Wallet: Already implemented
- Fortmatic: https://docs.fortmatic.com/web3-integration/web3-provider
- Coinbase Wallet: Probably behaves as a Browser Wallet
- Wallet Connect: https://docs.walletconnect.org/quick-start/dapps/web3-provider

**Comment by aggre** [comment]
@hhatto Can you integrate the owned Ethereum node to this feature?

Perhaps only browser wallets need to use the owned Ethereum nodes. (It can solve problems, especially in Trust Wallet)

FYI: https://github.com/dev-protocol/stakes.social/issues/403#issuecomment-716902479

**Comment by hhatto** [comment]
> @hhatto Can you integrate the owned Ethereum node to this feature?
> 
> Perhaps only browser wallets need to use the owned Ethereum nodes. (It can solve problems, especially in Trust Wallet)

@aggre OK, I can try 👍

**Comment by aggre** [comment]
@hhatto The owned Ethereum node is currently re-fetching blocks due to changes in geth parameters. I recommend mocking URL with Infura for the development as the blocks will be fragmented for a few days.
