### ISSUE TITLE
Use renewed header design

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#745]
Use the new header:

<img width="1363" alt="The new header design" src="https://user-images.githubusercontent.com/1970283/100176948-7b55bd00-2f14-11eb-8136-112100b56d44.png">

## Required update

1. "Uni Noue" is used as the theme font in the design, but the font is not included in the web font platforms we can use. Therefore, use Neue Haas Unica instead: https://fonts.adobe.com/fonts/neue-haas-unica _This font is already included in Adobe Fonts currently available on SS. Therefore, you can fix it by simply changing the body font family._

**Comment by defi-er** [comment]
Ok, Neue haas unica is good too!

**Comment by aggre** [comment]
SVG of 🥨 is here: https://www.dropbox.com/sh/s55ba1d7qlcixjy/AADpM9_cZZR9k2wCJdFzwZzoa?dl=0

**Comment by aggre** [comment]
I put the icon here: https://github.com/dev-protocol/stakes.social/issues/745#issuecomment-733420749

I think a good idea is separate the icon and "Stakes.social" typography by this issue.
