### ISSUE TITLE
Merge the `/portfolio` page into the `/author/[address]` page

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#746]
As the title says.

By the way, isn't the URL `/profile` more suitable than `/author`?

**Comment by defi-er** [comment]
Yes `/profile` is better because this will be where users can see an overview of their account once they connect their blockchain wallet.

**Comment by aggre** [comment]
That's nice.

My idea is this:
- `/profile`: Wallet connected user's profile 
- `/profile/[address]`: Specified user's profile
