### ISSUE TITLE
Do it really need a forced wallet connection?

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#776]
As soon as the user accesses the application, Stakes.social will request a wallet connection.

Requests that are irrelevant to users who just want to browse can hinder UX.

I think it is more appropriate to request a connection only when the user clicks "Sign in".

![](https://media1.tenor.com/images/04e9d5f6c2f5848a5dc199d6f0190be9/tenor.gif?itemid=12799633)

**Comment by Zezima-sudo** [comment]
yes, definitely. but, isn't this how it stakes.social already functions? i haven't been asked to provide wallet until i click 'Sign In'

**Comment by aggre** [comment]
I have confirmed this issue in MetaMask. If the MetaMask was previously connected and unlocked when I open Stakes.social, the connection request will not open.

However, the first time access, or when MetaMask is locked, the connection request will open.

**Comment by DomEscobar** [comment]
I think this is a good idea, especially for new users this is a direct scare off if they are immediately forced to take action

**Comment by defi-er** [comment]
The SSV3 only asked you to connect a wallet when you click sign-in to access profile. You don't need to access profile if you don't have a wallet.

**Comment by defi-er** [comment]
I'm not having this issue, nor intended this during the design process, but if it's appearing for others then I agree that the module should only appear when clicking "Sign In".
