### ISSUE TITLE
Provide a message for non supported browsers

### ISSUE THREAD

**Issue by DomEscobar** [dev-protocol/stakes.social#780]
Tested with : https://preview.stakes.social

**Desktop**

**IE 11:** 
Doesnt work - Shall we provide a message like "isn't supported" ? 

**Edge v44 Legacy**
Isnt loading. Console shows some errors

**Comment by aggre** [comment]
Thank you for cross-browser testing!

Internet Explorer or Edge Legacy is not supported. As you say, it would be nice to have a message that the app doesn't support it. (BTW, Edge built with Chromium is supported)

**Comment by DomEscobar** [comment]
Oh yes forgot to mention :D, okey I updated the title
