### ISSUE TITLE
Cover image upload functionality not working

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#815]
I tried to upload a new cover photo, and it ended up as two duplicates and now I cannot delete any of them.

<img width="590" alt="Screen Shot 2020-12-07 at 22 27 14" src="https://user-images.githubusercontent.com/170270/101369870-5cbfd080-38db-11eb-8414-fd6da1f90006.png">

The trash button doesn't do anything.

**Comment by aggre** [comment]
@hhatto Can you help us?

**Comment by aggre** [comment]
You can use `onRemove` handler of `antd.Upload`.

https://github.com/dev-protocol/stakes.social/blob/68f4ac710c81578687c1fb39efb902455662e4e8/packages/web/src/pages/author/%5BauthorAddress%5D/edit.tsx#L118-L140

https://ant.design/components/upload/
