### ISSUE TITLE
`undefined` in MetaMask message when signing a profile edit

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#816]
I updated a field in my profile, clicked saved, and MetaMask extension opened prompting me to sign, and the message there shows `undefined`:

<img width="279" alt="Screen Shot 2020-12-07 at 22 28 12" src="https://user-images.githubusercontent.com/170270/101370136-af00f180-38db-11eb-88f4-47176a57e836.png">

**Comment by aggre** [comment]
This issue has been fixed by #822
