### ISSUE TITLE
Include snippet for readme badge on the asset page

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#817]
For example, on https://stakes.social/0x7dC42FA19C5CfDfACdcf7B7bEeE9b6CfC77A6F1b, it would be nice if the author could quickly copy a snippet to add a DEV badge to the repo readme. I think making it easy to get the badge would encourage more authors to add it to their project's readme.

**Comment by aggre** [comment]
This can surely be built quickly. A snippet is as follows.

```markdown
[![Stake to support us](https://badge.devprotocol.xyz/ASSET_ADDRESS_STARTING_WITH_0x)](https://stakes.social/ASSET_ADDRESS_STARTING_WITH_0x)
```

Add this to the asset pages. And, we have [react-markdown](https://github.com/remarkjs/react-markdown) installed, so it is possible to preview markdown.

**Comment by sindresorhus** [comment]
I also think the badge could be a bit more actionable. It doesn't currently give people a strong urge to click it. Maybe also have a badge with text like "Support on DEV" / "Stake on DEV" / or something like that.
