### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#820]
I think connecting your GitHub profile could give a lot of nice discoverability improvements:

1. You could import the projects I follow or have starred and match them with existing assets, and suggest those for staking.
2. Import the people I follow on GitHub and show me if they have any projects that can be staked.
3. Import description from GitHub. Also, backfill descriptions for existing assets that lack one.

**Comment by defi-er** [comment]
This is on our roadmap for the upcoming release. It will also make importing profile pictures and bios easier.
