### ISSUE TITLE
Asset page does not show "creator reward"

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#825]
For example, on https://stakes.social/0x44d871aebF0126Bf646753E2C976Aa7e68A66c15, for "Your Rewards", it shows the reward I got when I incorrectly shortly staked my own project. It doesn't show the "creator reward".

**Comment by aggre** [comment]
Information for creators is required on the asset pages. These sections are irrelevant to the normal staking user, so it's best to show them only to users who have the Creator Tokens.

**Comment by Cold-A-Muse** [comment]
> Information for creators is required on the asset pages. These sections are irrelevant to the normal staking user, so it's best to show them only to users who have the Creator Tokens.

Is there a way to check who owns creator tokens of a property through GraphQL at the moment?

**Comment by aggre** [comment]
> Is there a way to check who owns creator tokens of a property through GraphQL at the moment?

@Cold-A-Muse Unfortunately, the GraphQL doesn't record token balances, so it can't be used as a conditional expression. But we can use the `useBalanceOfProperty` hook to check the balance. Use it like this:

https://github.com/dev-protocol/stakes.social/blob/89fbc079b9234201c2f03f1cb88d06516cbf9d71/packages/web/src/components/molecules/AssetItemOnList/index.tsx#L98

https://github.com/dev-protocol/stakes.social/blob/89fbc079b9234201c2f03f1cb88d06516cbf9d71/packages/web/src/components/molecules/AssetItemOnList/index.tsx#L107

Is this useful for you?

**Comment by sindresorhus** [comment]
Please keep it open.
