### ISSUE TITLE
Issue: Switching from stakes.social to other website causes errors to pop up

### ISSUE THREAD

**Issue by Cold-A-Muse** [dev-protocol/stakes.social#857]
As reported by user "Desu" in TG:

When you’re logged in and you decide to visit another website, this pops up
![image](https://user-images.githubusercontent.com/5823083/102331113-af0f8a00-3f8a-11eb-9d1f-ded11bd9ddb0.png)

We need to hide the overlay in production as it shows way too many things to the end user.

**Comment by hhatto** [comment]
@Cold-A-Muse 

Is the problem that there are too many error messages?
If so, you can control the maximum number of messages displayed by making the following changes:
```diff
diff --git a/packages/web/src/pages/_app.tsx b/packages/web/src/pages/_app.tsx
index 9af8a55..4491478 100644
--- a/packages/web/src/pages/_app.tsx
+++ b/packages/web/src/pages/_app.tsx
@@ -14,6 +14,7 @@ import Fortmatic from 'fortmatic'
 import WalletLink from 'walletlink'
 import { WEB3_PROVIDER_ENDPOINT } from 'src/fixtures/wallet/constants'
 import { getAccountAddress } from 'src/fixtures/wallet/utility'
+import { message } from 'antd'

 class NextApp extends App<AppInitialProps & WithApolloProps<{}>> {
   state = { isCurrencyDEV: true, web3: undefined, web3Modal: undefined }
@@ -90,6 +91,10 @@ class NextApp extends App<AppInitialProps & WithApolloProps<{}>> {
   }

   componentDidMount = () => {
+    message.config({
+      maxCount: 3
+    })
+
     this.web3Modal = new Web3Modal({
       network: 'mainnet',
       cacheProvider: true,
```

**Comment by Cold-A-Muse** [comment]
@hhatto just the fact that these errors appear when going to an different URL on the same tab is really strange

**Comment by Cold-A-Muse** [comment]
I am closing this issue as I think Hhato has self-assigned himself to a similar one made by Sindre
