### ISSUE TITLE
Make asset description required

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#863]
I don't think seeing

> Stake DEV tokens to provide funding for OSS projects so that they can maintain development.

on most assets is very useful.

---

Example:

<img width="1006" alt="Screen Shot 2020-12-17 at 11 57 42" src="https://user-images.githubusercontent.com/170270/102445867-139c1900-405f-11eb-9323-461bdc114f8a.png">

**Comment by Cold-A-Muse** [comment]
Would you prefer not having a description at all @sindresorhus ? What do you think @defi-er ?

**Comment by sindresorhus** [comment]
No, there's should be a description.

**Comment by Cold-A-Muse** [comment]
Do you have a suggestion for a different placeholder for the ones That don't have a description?

**Comment by sindresorhus** [comment]
For now, just show the placeholder, but when https://github.com/dev-protocol/stakes.social/issues/820 is done, the descriptions should be automatically populated from GitHub. And new additions should be required to have a description. This is all just my opinion though.

**Comment by Cold-A-Muse** [comment]
Yea I agree. This will be worked on in the future! I will close this issue and let's keep track of this in #820

**Comment by sindresorhus** [comment]
> And new additions should be required to have a description.

Is this done? If not, I don't think this should be closed.

**Comment by Cold-A-Muse** [comment]
Currently it is necessary to provide a project description when an application is being submitted :) 
![image](https://user-images.githubusercontent.com/5823083/102988410-26f22d00-4514-11eb-8fc9-682990b63db3.png)
