### ISSUE TITLE
Make badge more actionable

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#867]
I think the badge could be a bit more actionable. It doesn't currently give people a strong urge to click it. Maybe also have a badge with text like "Support on DEV" / "Stake on DEV" / or something like that.

I would also find a way to encourage asset owners to add the badge to their repos. More on that in https://github.com/dev-protocol/stakes.social/issues/866.

**Comment by aggre** [comment]
@sindresorhus Thank you for the proposal! That's right. I'm trying a new design. Do you think this design is too wide for an SVG badge?

![](https://badge-git-renew-title.devprtcl.now.sh/0x44d871aebF0126Bf646753E2C976Aa7e68A66c15)

https://badge-git-renew-title.devprtcl.now.sh/0x44d871aebF0126Bf646753E2C976Aa7e68A66c15

**Comment by sindresorhus** [comment]
Looks good to me. I would drop the `+`. `32.3k` is implied to be rounded anyway.

**Comment by aggre** [comment]
@sindresorhus I tweaked the badge and made it available by adding `/descriptive` to the path!

![](https://badge.devprotocol.xyz/0x44d871aebF0126Bf646753E2C976Aa7e68A66c15/descriptive)

https://badge.devprotocol.xyz/0x44d871aebF0126Bf646753E2C976Aa7e68A66c15/descriptive

**Comment by sindresorhus** [comment]
🙌🏻
