### ISSUE TITLE
Don't show header image placeholder when there's no header image

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#868]
For example, https://stakes.social/0x698Cc96Db00c6A9BF4A4b097e8f0F8Bb6c430d7A

<img width="1101" alt="Screen Shot 2020-12-17 at 12 26 11" src="https://user-images.githubusercontent.com/170270/102447668-0da83700-4063-11eb-85f8-7464e46397b0.png">

**Comment by Cold-A-Muse** [comment]
@aggre do you agree?

**Comment by aggre** [comment]
Ah, I see. I agree this point! That is almost not meaningful.

**Comment by sindresorhus** [comment]
I also think the header is too big even when there's an actual illustration in it. I would make it much smaller and move it to float on the right or something.

**Comment by sindresorhus** [comment]
Please keep this open.
