### ISSUE TITLE
Make it easier to buy DEV

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#873]
Scenario: I have a DEV badge in my repos. A user wants to support me by staking one of my projects. They know nothing about cryptocurrency. When they land on my asset pool page, they see a "Buy DEV" button. It just opens Uniswap. The user has no idea how to go from fiat USD to DEV. I think the "Buy DEV" button should open a modal that explains the situation better and give some options.

Is there any service that makes it super easy to buy ETH with fiat which we could recommend in such a modal?

The ideal scenario is that there a way to have some kind of automatic "user's USD => USD to ETH => Uniswap => DEV" flow.

**Comment by Cold-A-Muse** [comment]
I had been thinking of something like this as well. There are solutions that allow u to directly purchase ETH with your bank card such as https://www.moonpay.com/. I think @defi-er might have some opinions on this :)?

**Comment by aggre** [comment]
I am also considering this issue. Ideally, Stakes.social should use user-friendly APIs to get cryptocurrencies—for example, Moonpay. (However, the tedious KYC process still stands in front of a user)

**Comment by voidzero** [comment]
I'm pretty much the person you're talking about, knowing nothing. I figured out how to go from fiat to DEV, but now I want to stake it and have no idea how.

**Comment by sindresorhus** [comment]
Please keep this open.
