### ISSUE TITLE
Badge shows `NaN` when there are no stakers

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#947]
<img width="88" alt="Screen Shot 2021-01-20 at 01 22 28" src="https://user-images.githubusercontent.com/170270/105076735-0939c880-5abe-11eb-83f9-640760293475.png">

**Comment by aggre** [comment]
@sindresorhus Can you tell me the Property address when this problem happens?

---

The following badges are not staked:

![](https://badge.devprotocol.xyz/0x698Cc96Db00c6A9BF4A4b097e8f0F8Bb6c430d7A/descriptive)

![](https://badge.devprotocol.xyz/0x698Cc96Db00c6A9BF4A4b097e8f0F8Bb6c430d7A)

**Comment by sindresorhus** [comment]
It was at: https://stakes.social/0xf871c71D64a3429fe3231aC5C8E7d044Ac25a00C

I cannot reproduce anymore. Weird.
