### ISSUE TITLE
Dev GraphQL will no longer supports author, name, and symbol of Properties

### ISSUE THREAD

**Issue by aggre** [dev-protocol/stakes.social#970]
Dev GraphQL will no longer support the following information for all Properties.
- `name`
- `symbol`
- `totalSupply`

Dev GraphQL provides them until this issue is closed, but the old information may be returned when after this PR (https://github.com/dev-protocol/protocol/pull/710) is merged.

Stakes.social will need to use Dev Kit to get native data from Ethereum instead of Dev GraphQL.

**Comment by Akira-Taniguchi** [comment]
Can I also add "totalSupply"?
This will eliminate the need for the property_meta table and simplify the server-side processing.
@aggre

**Comment by aggre** [comment]
Yes, `totalSupply` should also be added

**Comment by Akira-Taniguchi** [comment]
memo

The property_meta table itself survives, as it is used to get a list of properties using author as a key.
We plan to detect and update the property author when it is changed, but the name and symbol will remain the same, so please refer to the data on the blockchain.
